<?php

return [
    [
        'key'  => 'marketplace',
        'name' => 'marketplace::app.admin.configuration.index.marketplace.title',
        'info' => 'marketplace::app.admin.configuration.index.marketplace.info',
        'sort' => 1,
    ], [
        'key'  => 'marketplace.settings',
        'name' => 'marketplace::app.admin.configuration.index.marketplace.title',
        'info' => 'marketplace::app.admin.configuration.index.marketplace.info',
        'icon' => 'settings/settings.svg',
        'sort' => 1,
    ], [
        'key'    => 'marketplace.settings.information',
        'name'   => 'marketplace::app.admin.configuration.index.marketplace.module-info.title',
        'info'   => 'marketplace::app.admin.configuration.index.marketplace.module-info.info',
        'sort'   => 1,
        'fields' => [
            [
                'name'  => '',
                'title' => 'marketplace::app.admin.configuration.index.marketplace.module-info.app-version',
                'type'  => '',
            ],
        ],
    ], [
        'key'    => 'marketplace.settings.general',
        'name'   => 'marketplace::app.admin.configuration.index.marketplace.general.title',
        'info'   => 'marketplace::app.admin.configuration.index.marketplace.general.description',
        'sort'   => 2,
        'fields' => [
            [
                'name'          => 'status',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.general.status',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'          => 'lines_in_street_address',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.general.lines-in-street-address',
                'info'          => 'marketplace::app.admin.configuration.index.marketplace.general.lines-in-street-address-info',
                'type'          => 'text',
                'validation'    => 'integer|between:1,4',
            ], [
                'name'          => 'admin_commission_percentage',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.general.admin-commission-percentage',
                'type'          => 'text',
                'validation'    => 'required|between:1,100',
                'channel_based' => true,
                'locale_based'  => false,
            ],
        ],
    ], [
        'key'    => 'marketplace.settings.product',
        'name'   => 'marketplace::app.admin.configuration.index.marketplace.product.title',
        'info'   => 'marketplace::app.admin.configuration.index.marketplace.product.description',
        'sort'   => 2,
        'fields' => [
            [
                'name'          => 'approval_required',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.product.approval-required',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'          => 'seller_can_assign',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.product.seller-can-assign-product',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'          => 'seller_can_create',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.product.seller-can-create-product',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'          => 'show_progress_bar',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.product.show-progress-bar',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'          => 'flag_enabled',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.product.enable-flag',
                'type'          => 'boolean',
                'channel_based' => true,
            ],
        ],
    ], [
        'key'    => 'marketplace.settings.seller',
        'name'   => 'marketplace::app.admin.configuration.index.marketplace.seller.title',
        'info'   => 'marketplace::app.admin.configuration.index.marketplace.seller.description',
        'sort'   => 2,
        'fields' => [
            [
                'name'          => 'approval_required',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.seller.approval-required',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'          => 'can_create_invoice',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.seller.can-create-invoice',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'          => 'can_create_shipment',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.seller.can-create-shipment',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'          => 'can_cancel_order',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.seller.can-cancel-order',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'          => 'enable_minimum_order_amount',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.seller.enable-minimum-order-amount',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'          => 'flag_enabled',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.seller.enable-flag',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'          => 'show_red_flag',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.seller.show-red-flag',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'       => 'red_flag_limit',
                'title'      => 'marketplace::app.admin.configuration.index.marketplace.seller.red-flag-limit',
                'info'       => 'marketplace::app.admin.configuration.index.marketplace.seller.red-flag-limit-info',
                'type'       => 'text',
                'validation' => 'required|integer|min:1',
            ],
        ],
    ], [
        'key'    => 'marketplace.settings.featured_sellers',
        'name'   => 'marketplace::app.admin.configuration.index.marketplace.featured-sellers.title',
        'info'   => 'marketplace::app.admin.configuration.index.marketplace.featured-sellers.description',
        'sort'   => 2,
        'fields' => [
            [
                'name'          => 'status',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.featured-sellers.status',
                'type'          => 'boolean',
                'channel_based' => true,
            ], [
                'name'          => 'limit_count',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.featured-sellers.limit-count',
                'type'          => 'text',
                'validation'    => 'required|numeric',
                'channel_based' => true,
            ], [
                'name'          => 'popularity_criteria',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.featured-sellers.popularity-criteria.title',
                'type'          => 'select',
                'validation'    => 'required',
                'channel_based' => true,
                'options'       => [
                    [
                        'title' => 'marketplace::app.admin.configuration.index.marketplace.featured-sellers.popularity-criteria.all',
                        'value' => 'all',
                    ], [
                        'title' => 'marketplace::app.admin.configuration.index.marketplace.featured-sellers.popularity-criteria.maximum-orders',
                        'value' => 'maximum-orders',
                    ], [
                        'title' => 'marketplace::app.admin.configuration.index.marketplace.featured-sellers.popularity-criteria.maximum-products',
                        'value' => 'maximum-products',
                    ], [
                        'title' => 'marketplace::app.admin.configuration.index.marketplace.featured-sellers.popularity-criteria.maximum-rating',
                        'value' => 'maximum-rating',
                    ], [
                        'title' => 'marketplace::app.admin.configuration.index.marketplace.featured-sellers.popularity-criteria.maximum-sale',
                        'value' => 'maximum-sales',
                    ],
                ],
            ],
        ],
    ], [
        'key'    => 'marketplace.settings.landing_page',
        'name'   => 'marketplace::app.admin.configuration.index.marketplace.landing-page.title',
        'info'   => 'marketplace::app.admin.configuration.index.marketplace.landing-page.description',
        'sort'   => 3,
        'fields' => [
            [
                'name'          => 'banner_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.banner-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'banner_description',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.banner-description',
                'type'          => 'textarea',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'banner_btn_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.banner-btn-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'banner_image',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.banner-image',
                'type'          => 'image',
                'validation'    => 'mimes:jpeg,bmp,png,jpg',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'community_count',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.community-count',
                'type'          => 'number',
                'validation'    => 'numeric',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'business_hour',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.business-hour',
                'type'          => 'text',
                'validation'    => 'required|alpha_num',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'payment_duration',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.payment-duration',
                'type'          => 'number',
                'validation'    => 'required|numeric',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'serviceable_pincode',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.serviceable-pincode',
                'type'          => 'number',
                'validation'    => 'required|numeric',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'feature_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'feature_description',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-description',
                'type'          => 'textarea',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'feature_image',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-image',
                'type'          => 'image',
                'validation'    => 'mimes:jpeg,bmp,png,jpg',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'feature_box1_icon',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-box1-icon',
                'type'          => 'image',
                'validation'    => 'mimes:jpeg,bmp,png,jpg',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'feature_box1_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-box1-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'feature_box1_desc',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-box1-desc',
                'type'          => 'textarea',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'feature_box2_icon',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-box2-icon',
                'type'          => 'image',
                'validation'    => 'mimes:jpeg,bmp,png,jpg',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'feature_box2_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-box2-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'feature_box2_desc',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-box2-desc',
                'type'          => 'textarea',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'feature_box3_icon',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-box3-icon',
                'type'          => 'image',
                'validation'    => 'mimes:jpeg,bmp,png,jpg',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'feature_box3_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-box3-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'feature_box3_desc',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-box3-desc',
                'type'          => 'textarea',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'feature_box4_icon',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-box4-icon',
                'type'          => 'image',
                'validation'    => 'mimes:jpeg,bmp,png,jpg',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'feature_box4_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-box4-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'feature_box4_desc',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.feature-box4-desc',
                'type'          => 'textarea',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'journey_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'journey_description',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-description',
                'type'          => 'textarea',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'journey_step1_icon',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step1-icon',
                'type'          => 'image',
                'validation'    => 'mimes:jpeg,bmp,png,jpg',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'journey_step1_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step1-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'journey_step1_desc',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step1-desc',
                'type'          => 'textarea',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'journey_step2_icon',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step2-icon',
                'type'          => 'image',
                'validation'    => 'mimes:jpeg,bmp,png,jpg',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'journey_step2_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step2-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'journey_step2_desc',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step2-desc',
                'type'          => 'textarea',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'journey_step3_icon',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step3-icon',
                'type'          => 'image',
                'validation'    => 'mimes:jpeg,bmp,png,jpg',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'journey_step3_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step3-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'journey_step3_desc',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step3-desc',
                'type'          => 'textarea',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'journey_step4_icon',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step4-icon',
                'type'          => 'image',
                'validation'    => 'mimes:jpeg,bmp,png,jpg',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'journey_step4_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step4-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'journey_step4_desc',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step4-desc',
                'type'          => 'textarea',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'journey_step5_icon',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step5-icon',
                'type'          => 'image',
                'validation'    => 'mimes:jpeg,bmp,png,jpg',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'journey_step5_title',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step5-title',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'journey_step5_desc',
                'title'         => 'marketplace::app.admin.configuration.index.marketplace.landing-page.journey-step5-desc',
                'type'          => 'textarea',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ],
        ],
    ],
];
